import React from 'react'
import { fetchCSV } from './utils/csv'

type Player={id:string;name:string;level:string;club?:string;ig?:string;photo?:string}
const defaultConfig={formUrl:'https://forms.gle/TU_FORMULARIO',instagram:'https://instagram.com/tu_cuenta_ig',playersCsv:'players.csv'}
function useAppConfig(){const[cfg,setCfg]=React.useState(defaultConfig);React.useEffect(()=>{fetch(`${import.meta.env.BASE_URL}app-config.json`).then(r=>r.ok?r.json():defaultConfig).then(setCfg).catch(()=>setCfg(defaultConfig))},[]);return cfg}
function mapPlayers(data:any[]){return data.map((r:any,idx:number)=>({id:r.id||String(idx),name:r.name||r.nombre||r.Name||'Jugador',level:r.level||r.nivel||r.Level||'',club:r.club||'',ig:r.ig||r.instagram||'',photo:r.photo||r.foto||''}))}
function usePlayers(playersCsv:string){const[players,setPlayers]=React.useState<Player[]>([]);React.useEffect(()=>{(async()=>{try{const url=playersCsv.startsWith('http')?playersCsv:`${import.meta.env.BASE_URL}${playersCsv}`;let data=await fetchCSV(url);if(!Array.isArray(data)||data.length===0)throw new Error('empty');setPlayers(mapPlayers(data))}catch{try{const localUrl=`${import.meta.env.BASE_URL}players.csv`;const data=await fetchCSV(localUrl);setPlayers(mapPlayers(data))}catch{setPlayers([])}}})()},[playersCsv]);return players}
const GALLERY=[{src:'https://images.unsplash.com/photo-1513245543132-31f507417b26?q=80&auto=format&fit=crop',alt:'Pozo 1'},{src:'https://images.unsplash.com/photo-1520975922192-24cd97bca3d5?q=80&auto=format&fit=crop',alt:'Pozo 2'},{src:'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&auto=format&fit=crop',alt:'Pozo 3'},{src:'https://images.unsplash.com/photo-1552074280-9d5c3b0a3f6a?q=80&auto=format&fit=crop',alt:'Pozo 4'},{src:'https://images.unsplash.com/photo-1508672019048-805c876b67e2?q=80&auto=format&fit=crop',alt:'Pozo 5'},{src:'https://images.unsplash.com/photo-1530023367847-a683933f417f?q=80&auto=format&fit=crop',alt:'Pozo 6'}]
function Nav({formUrl}:{formUrl:string}){return(<header className='sticky top-0 z-40 w-full backdrop-blur bg-white/70 border-b border-slate-200'><div className='mx-auto max-w-[1100px] px-4 md:px-6 h-14 flex items-center justify-between'><a href='#' className='font-semibold text-slate-800'>J & S Padel</a><nav className='hidden md:flex gap-6 text-sm'><a href='#inscripcion' className='text-slate-600 hover:text-slate-900'>Inscripción</a><a href='#redes' className='text-slate-600 hover:text-slate-900'>Redes</a><a href='#galeria' className='text-slate-600 hover:text-slate-900'>Galería</a><a href='#jugadores' className='text-slate-600 hover:text-slate-900'>Jugadores</a><a href='#faq' className='text-slate-600 hover:text-slate-900'>FAQ</a></nav><a href={formUrl} target='_blank' className='rounded-xl bg-cyan-500 text-white text-sm px-3 py-2 hover:bg-cyan-600 transition'>Inscríbete</a></div></header>)}
function Hero({formUrl}:{formUrl:string}){return(<section className='relative'><div className='mx-auto max-w-[1100px] px-4 md:px-6 py-14 md:py-20'><div className='grid md:grid-cols-2 gap-10 items-center'><div><h1 className='text-4xl md:text-5xl font-bold tracking-tight text-slate-900'>Torneos tipo <span className='bg-gradient-to-r from-cyan-500 to-violet-500 bg-clip-text text-transparent'>POZO</span><br/> rápidos, justos y divertidos</h1><p className='mt-4 text-slate-600'>Organizamos pozos de ~2h en instalaciones municipales. Inscríbete, ve fotos y consulta perfiles de jugadores.</p><ul className='mt-4 text-slate-600 text-sm space-y-1'><li>• Próximo pozo: <b>Fecha por confirmar</b></li><li>• Ubicación: <b>Instalaciones municipales</b></li><li>• Formato: rotación por niveles</li></ul><div className='mt-6 flex flex-wrap gap-3'><a href={formUrl} target='_blank' className='rounded-2xl bg-slate-900 text-white px-5 py-2.5 text-sm hover:-translate-y-0.5 transition'>Abrir formulario</a><a href='#jugadores' className='rounded-2xl border border-slate-300 px-5 py-2.5 text-sm hover:bg-slate-50 transition'>Ver jugadores</a></div></div><div className='rounded-3xl h-56 md:h-72 bg-gradient-to-br from-cyan-100 to-violet-100 border border-slate-200 shadow-inner'/></div></div></section>)}
function Inscripcion({formUrl}:{formUrl:string}){return(<section id='inscripcion' className='border-t border-slate-200'><div className='mx-auto max-w-[1100px] px-4 md:px-6 py-12'><h2 className='text-xl font-semibold text-slate-900'>Inscripción</h2><p className='text-slate-600 mt-2'>Completa el formulario para confirmar tu plaza.</p><a href={formUrl} target='_blank' className='mt-4 inline-block rounded-xl bg-cyan-500 text-white px-5 py-2.5 text-sm hover:bg-cyan-600 transition'>Abrir formulario</a></div></section>)}
function Redes({instagram}:{instagram:string}){return(<section id='redes' className='border-t border-slate-200'><div className='mx-auto max-w-[1100px] px-4 md:px-6 py-12'><h2 className='text-xl font-semibold text-slate-900'>Redes</h2><p className='text-slate-600 mt-2'>Síguenos y etiqueta tus fotos del pozo 😊</p><a href={instagram} target='_blank' className='mt-4 inline-block rounded-xl border border-slate-300 px-5 py-2.5 text-sm hover:bg-slate-50 transition'>Instagram</a></div></section>)}
function Galeria(){const items=GALLERY;return(<section id='galeria' className='border-t border-slate-200'><div className='mx-auto max-w-[1100px] px-4 md:px-6 py-12'><h2 className='text-xl font-semibold text-slate-900'>Galería</h2><p className='text-slate-600 mt-2'>Las mejores fotos de torneos anteriores.</p><div className='mt-6 grid grid-cols-2 md:grid-cols-3 gap-3'>{items.map((g,i)=>(<figure key={i} className='group rounded-2xl overflow-hidden border border-slate-200'><img src={g.src} alt={g.alt} loading='lazy' className='w-full h-40 md:h-48 object-cover group-hover:scale-[1.02] transition' srcSet={`${g.src}&w=400 400w, ${g.src}&w=800 800w`} sizes='(max-width: 768px) 50vw, 33vw'/><figcaption className='flex items-center justify-between p-2 text-xs text-slate-600'>{g.alt}<a href={g.src} download className='text-cyan-600 hover:underline'>Descargar</a></figcaption></figure>))}</div></div></section>)}
function Jugadores({players}:{players:Player[]}){const[q,setQ]=React.useState('');const list=React.useMemo(()=>{const t=q.trim().toLowerCase();if(!t)return players;return players.filter(p=>p.name.toLowerCase().includes(t)||(p.level?.toLowerCase().includes(t))||(p.club?.toLowerCase().includes(t)))},[q,players]);return(<section id='jugadores' className='border-t border-slate-200'><div className='mx-auto max-w-[1100px] px-4 md:px-6 py-12'><div className='flex items-end justify-between gap-4'><div><h2 className='text-xl font-semibold text-slate-900'>Jugadores</h2><p className='text-slate-600 mt-2'>Busca por nombre, nivel o club. (Fuente: Google Sheet o CSV local)</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Buscar…' className='w-48 md:w-64 rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-cyan-400'/></div><div className='mt-6 grid sm:grid-cols-2 md:grid-cols-3 gap-4'>{list.map(p=>(<div key={p.id} className='rounded-2xl border border-slate-200 p-4 flex gap-3 items-center'><img src={p.photo||'https://i.pravatar.cc/100'} alt={p.name} className='w-14 h-14 rounded-full object-cover'/><div className='min-w-0'><div className='font-medium text-slate-900 truncate'>{p.name}</div><div className='text-xs text-slate-500 truncate'>{p.level}{p.club?` · ${p.club}`:''}</div>{p.ig&&(<a href={`https://instagram.com/${p.ig.replace('@','')}`} target='_blank' className='text-xs text-cyan-600 hover:underline'>{p.ig}</a>)}</div></div>))}</div></div></section>)}
function Faq(){const items=[{q:'¿Cómo funciona un pozo?',a:'Partidos cortos (~10-12min), rotación por niveles, sumas puntos, ranking y finales.'},{q:'¿Nivel mínimo/recomendado?',a:'Aceptamos todos los niveles. Indícalo en el formulario para equilibrar grupos.'},{q:'¿Qué debo llevar?',a:'Pala, agua y muchas ganas :)'}];return(<section id='faq' className='border-t border-slate-200'><div className='mx-auto max-w-[1100px] px-4 md:px-6 py-12'><h2 className='text-xl font-semibold mb-4'>Preguntas frecuentes</h2><div className='divide-y'>{items.map((it,i)=>(<details key={i} className='py-3 group'><summary className='cursor-pointer font-medium text-slate-800'>{it.q}</summary><p className='mt-2 text-slate-600'>{it.a}</p></details>))}</div></div></section>)}
function Footer(){return(<footer className='border-top border-slate-200'><div className='mx-auto max-w-[1100px] px-4 md:px-6 py-10 text-xs text-slate-500'>© {new Date().getFullYear()} J & S Padel — Pozo.</div></footer>)}
export default function App(){const cfg=useAppConfig();const players=usePlayers(cfg.playersCsv);return(<div className='bg-white text-slate-900'><Nav formUrl={cfg.formUrl}/><Hero formUrl={cfg.formUrl}/><Inscripcion formUrl={cfg.formUrl}/><Redes instagram={cfg.instagram}/><Galeria/><Jugadores players={players}/><Faq/><Footer/></div>)}
